<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Toko berhasil didaftarkananda dapat men_b3a8bd</name>
   <tag></tag>
   <elementGuidId>6eed249e-9c94-4ff7-85b0-bbc595e7c5b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d6624744-88d2-493a-bb30-7d0e345d514c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>68ba6ade-6f41-4524-ba1c-0d43e3081ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8181ce2a-db33-47f3-a067-e6d80b66bccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>toast-1-title</value>
      <webElementGuid>4cd3ccb0-327b-4e40-885f-82730abd7071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-alert css-1hp6ttu</value>
      <webElementGuid>a7ba6889-1733-4354-ab41-dcc298b1377b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toko berhasil didaftarkananda dapat menggunakan login sekarang</value>
      <webElementGuid>0f3c15af-0666-4b96-9775-756df5a2c013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-toast-manager-top-right&quot;)/li[@class=&quot;chakra-toast&quot;]/div[@class=&quot;chakra-toast__inner&quot;]/div[@id=&quot;1&quot;]</value>
      <webElementGuid>77d99d74-ed40-4113-979d-10f0f73a3d6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='1']</value>
      <webElementGuid>9b5f981e-d9da-4087-948a-7896006924f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='chakra-toast-manager-top-right']/li/div/div</value>
      <webElementGuid>29780bc3-0948-48ee-b207-f49822506afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>27faa9a0-d9db-4871-be8d-36192df1eb50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '1' and (text() = 'Toko berhasil didaftarkananda dapat menggunakan login sekarang' or . = 'Toko berhasil didaftarkananda dapat menggunakan login sekarang')]</value>
      <webElementGuid>74374562-7dfb-4974-b992-fa709a960677</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
